default['group']['list']=['devops','buildteam']
default['devops']=['bastionuser','ameen','sudhakar','praveen']
default['buildteam']=['madan','sriram']
default['dbateam']=['yudu']
default['developers']=['balaji.k','sundar']
